#!/bin/sh

BASE=$PWD

cd $PWD/modules/codec

rename it.tidalwave.imageio.arw.ARWImageReader 		org.rawdarkroom.codec.impl.minolta.ArwImageReader
rename it.tidalwave.imageio.arw.ARWImageReaderSpi 		org.rawdarkroom.codec.impl.minolta.ArwImageReaderSpi
rename it.tidalwave.imageio.arw.ARWMakerNote 			org.rawdarkroom.metadata.minolta.ArwMakerNote
rename it.tidalwave.imageio.arw.ARWMetadata 			org.rawdarkroom.metadata.minolta.ArwMetadata
rename it.tidalwave.imageio.arw.ARWRasterReader 		org.rawdarkroom.codec.impl.minolta.ArwRasterReader
rename it.tidalwave.imageio.cr2.CR2ImageReader 		org.rawdarkroom.codec.impl.canon.Cr2ImageReader
rename it.tidalwave.imageio.cr2.CR2ImageReaderSpi 		org.rawdarkroom.codec.impl.canon.Cr2ImageReaderSpi
rename it.tidalwave.imageio.cr2.CR2Metadata 			org.rawdarkroom.metadata.canon.Cr2Metadata
rename it.tidalwave.imageio.cr2.CR2RasterReader 		org.rawdarkroom.codec.impl.canon.Cr2RasterReader
rename it.tidalwave.imageio.cr2.CR2SensorInfo 			org.rawdarkroom.metadata.canon.Cr2SensorInfo
rename it.tidalwave.imageio.cr2.CanonCR2MakerNote 		org.rawdarkroom.metadata.canon.CanonCr2MakerNote
rename it.tidalwave.imageio.crw.CIFFTag 			org.rawdarkroom.metadata.canon.CiffTag
rename it.tidalwave.imageio.crw.CRWImageInputStream 		org.rawdarkroom.codec.impl.canon.CrwImageInputStream
rename it.tidalwave.imageio.crw.CRWImageReader 		org.rawdarkroom.codec.impl.canon.CrwImageReader
rename it.tidalwave.imageio.crw.CRWImageReaderSpi 		org.rawdarkroom.codec.impl.canon.CrwImageReaderSpi
rename it.tidalwave.imageio.crw.CRWRasterReader 		org.rawdarkroom.codec.impl.canon.CrwRasterReader
rename it.tidalwave.imageio.crw.CanonCRWMakerNote 		org.rawdarkroom.metadata.canon.CanonCrwMakerNote
rename it.tidalwave.imageio.dcr.DCRImageReader 		org.rawdarkroom.codec.impl.kodak.DcrImageReader
rename it.tidalwave.imageio.dcr.DCRImageReaderSpi 		org.rawdarkroom.codec.impl.kodak.DcrImageReaderSpi
rename it.tidalwave.imageio.dcr.DCRMetadata 			org.rawdarkroom.metadata.kodak.DcrMetadata
rename it.tidalwave.imageio.dcr.DCRRasterReader 		org.rawdarkroom.codec.impl.kodak.DcrRasterReader
rename it.tidalwave.imageio.dcr.KodakMakerNote 		org.rawdarkroom.metadata.kodak.KodakDcrMakerNote
rename it.tidalwave.imageio.decoder.HuffmannDecoder 		org.rawdarkroom.spi.decoder.HuffmannDecoder
rename it.tidalwave.imageio.decoder.LosslessJPEGDecoder 	org.rawdarkroom.spi.decoder.LosslessJpegDecoder
rename it.tidalwave.imageio.dng.DNGImageReader 		org.rawdarkroom.codec.impl.adobe.DngImageReader
rename it.tidalwave.imageio.dng.DNGImageReaderSpi 		org.rawdarkroom.codec.impl.adobe.DngImageReaderSpi
rename it.tidalwave.imageio.dng.DNGMetadata 			org.rawdarkroom.metadata.adobe.DngMetadata
rename it.tidalwave.imageio.dng.DNGRasterReader 		org.rawdarkroom.codec.impl.adobe.DngRasterReader
rename it.tidalwave.imageio.io.BitReader 			org.rawdarkroom.spi.codec.BitReader
rename it.tidalwave.imageio.io.FastBitReader 			org.rawdarkroom.spi.codec.FastBitReader
rename it.tidalwave.imageio.io.FileImageInputStream2 		org.rawdarkroom.spi.codec.FileImageInputStream2
rename it.tidalwave.imageio.io.FileImageInputStream2Spi 	org.rawdarkroom.spi.codec.FileImageInputStream2Spi
rename it.tidalwave.imageio.io.RAWImageInputStream 		org.rawdarkroom.spi.codec.RawImageInputStream
rename it.tidalwave.imageio.io.RAWImageInputStreamImpl 	org.rawdarkroom.spi.codec.RawImageInputStreamImpl
rename it.tidalwave.imageio.io.SixteenBitsReader 		org.rawdarkroom.spi.codec.SixteenBitsReader
rename it.tidalwave.imageio.io.TwelveBitsReader 		org.rawdarkroom.spi.codec.TwelveBitsReader
rename it.tidalwave.imageio.makernote.LeicaMakerNote i		org.rawdarkroom.metadata.leica.LeicaMakerNote
rename it.tidalwave.imageio.minolta.MinoltaRawData 		org.rawdarkroom.metadata.minolta.MinoltaRawData
rename it.tidalwave.imageio.mrw.MRWHeaderProcessor 		org.rawdarkroom.codec.impl.MrwHeaderProcessor
rename it.tidalwave.imageio.mrw.MRWImageReader 		org.rawdarkroom.codec.impl.MrwImageReader
rename it.tidalwave.imageio.mrw.MRWImageReaderSpi 		org.rawdarkroom.codec.impl.MrwImageReaderSpi
rename it.tidalwave.imageio.mrw.MRWMetadata 			org.rawdarkroom.metadata.minolta.MrwMetadata
rename it.tidalwave.imageio.mrw.MRWRasterReader 		org.rawdarkroom.codec.impl.minolta.MrwRasterReader
rename it.tidalwave.imageio.mrw.MinoltaMakerNote 		org.rawdarkroom.metadata.minolta.MinoltaMakerNote
rename it.tidalwave.imageio.nef.NDFRasterReader 		org.rawdarkroom.codec.impl.nikon.NdfRasterReader
rename it.tidalwave.imageio.nef.NEFHeaderProcessor 		org.rawdarkroom.codec.impl.nikon.NefHeaderProcessor
rename it.tidalwave.imageio.nef.NEFImageReader 		org.rawdarkroom.codec.impl.nikon.NefImageReader
rename it.tidalwave.imageio.nef.NEFImageReaderSpi 		org.rawdarkroom.codec.impl.nikon.NefImageReaderSpi
rename it.tidalwave.imageio.nef.NEFLinearizationTable 		org.rawdarkroom.metadata.nikon.NefLinearizationTable
rename it.tidalwave.imageio.nef.NEFMetadata 			org.rawdarkroom.metadata.nikon.NefMetadata
rename it.tidalwave.imageio.nef.NEFRasterReader 		org.rawdarkroom.codec.impl.nikon.NefRasterReader
rename it.tidalwave.imageio.nef.NEFWhiteBalanceInfo 		org.rawdarkroom.metadata.nikon.NefWhiteBalanceInfo
rename it.tidalwave.imageio.nef.NikonLensInfo 			org.rawdarkroom.metadata.nikon.NikonLensInfo
rename it.tidalwave.imageio.nef.NikonMakerNote3 		org.rawdarkroom.metadata.nikon.NikonMakerNote3
rename it.tidalwave.imageio.nef.RasterReaderCoolpix 		org.rawdarkroom.codec.impl.nikon.RasterReaderCoolpix
rename it.tidalwave.imageio.nef.RasterReader_NIKON_D100 	org.rawdarkroom.codec.impl.nikon.RasterReader_NIKON_D100
rename it.tidalwave.imageio.nef.RasterReader_NIKON_D3 		org.rawdarkroom.codec.impl.nikon.RasterReader_NIKON_D3
rename it.tidalwave.imageio.orf.CSeriesRasterReader 		org.rawdarkroom.codec.impl.olympus.CSeriesRasterReader
rename it.tidalwave.imageio.orf.CameraSettings 		org.rawdarkroom.metadata.olympus.CameraSettings
rename it.tidalwave.imageio.orf.E300RasterReader 		org.rawdarkroom.codec.impl.olympus.E300RasterReader
rename it.tidalwave.imageio.orf.E410RasterReader 		org.rawdarkroom.codec.impl.olympus.E410RasterReader
rename it.tidalwave.imageio.orf.Equipment 			org.rawdarkroom.metadata.olympus.Equipment
rename it.tidalwave.imageio.orf.FocusInfo 			org.rawdarkroom.metadata.olympus.FocusInfo
rename it.tidalwave.imageio.orf.ImageProcessing 		org.rawdarkroom.metadata.olympus.ImageProcessing
rename it.tidalwave.imageio.orf.ORFImageReader 		org.rawdarkroom.codec.impl.olympus.OrfImageReader
rename it.tidalwave.imageio.orf.ORFImageReaderSpi 		org.rawdarkroom.codec.impl.olympus.OrfImageReaderSpi
rename it.tidalwave.imageio.orf.ORFMetadata 			org.rawdarkroom.metadata.olympus.OrfMetadata
rename it.tidalwave.imageio.orf.ORFRasterReader 		org.rawdarkroom.codec.impl.olympus.OrfRasterReader
rename it.tidalwave.imageio.orf.OlympusMakerNote 		org.rawdarkroom.metadata.olympus.OlympusMakerNote
rename it.tidalwave.imageio.orf.RawDevelopment 		org.rawdarkroom.metadata.olympus.RawDevelopment
rename it.tidalwave.imageio.orf.SPRasterReader 		org.rawdarkroom.codec.impl.olympus.SPRasterReader
rename it.tidalwave.imageio.pef.PEFDecoder 			org.rawdarkroom.codec.impl.pentax.PefDecoder
rename it.tidalwave.imageio.pef.PEFImageReader 		org.rawdarkroom.codec.impl.pentax.PefImageReader
rename it.tidalwave.imageio.pef.PEFImageReaderSpi 		org.rawdarkroom.codec.impl.pentax.PefImageReaderSpi
rename it.tidalwave.imageio.pef.PEFMetadata 			org.rawdarkroom.metadata.pentax.PefMetadata
rename it.tidalwave.imageio.pef.PEFRasterReader 		org.rawdarkroom.codec.impl.pentax.PefRasterReader
rename it.tidalwave.imageio.pef.PentaxMakerNote 		org.rawdarkroom.metadata.pentax.PentaxMakerNote
rename it.tidalwave.imageio.raf.FujiMakerNote 			org.rawdarkroom.metadata.fuji.FujiMakerNote
rename it.tidalwave.imageio.raf.FujiRawData 			org.rawdarkroom.metadata.fuji.FujiRawData
rename it.tidalwave.imageio.raf.FujiTable1 			org.rawdarkroom.metadata.fuji.FujiTable1
rename it.tidalwave.imageio.raf.RAFHeaderProcessor 		org.rawdarkroom.codec.impl.fuji.RafHeaderProcessor
rename it.tidalwave.imageio.raf.RAFImageReader 		org.rawdarkroom.codec.impl.fuji.RafImageReader
rename it.tidalwave.imageio.raf.RAFImageReaderSpi 		org.rawdarkroom.codec.impl.fuji.RafImageReaderSpi
rename it.tidalwave.imageio.raf.RAFMetadata 			org.rawdarkroom.metadata.fuji.RafMetadata
rename it.tidalwave.imageio.raf.RAFRasterReader 		org.rawdarkroom.codec.impl.fuji.RafRasterReader
rename it.tidalwave.imageio.raw.AbstractTag 			org.rawdarkroom.metadata.AbstractTag
rename it.tidalwave.imageio.raw.Directory 			org.rawdarkroom.metadata.Directory
rename it.tidalwave.imageio.raw.HeaderProcessor 		org.rawdarkroom.codec.spi.HeaderProcessor
rename it.tidalwave.imageio.raw.Packed12RasterReader 		org.rawdarkroom.codec.spi.Packed12RasterReader
rename it.tidalwave.imageio.raw.PostProcessor 			org.rawdarkroom.processor.Processor
rename it.tidalwave.imageio.raw.RAWImageReadParam 		org.rawdarkroom.RawImageReadParam
rename it.tidalwave.imageio.raw.RAWImageReaderSpiSupport 	org.rawdarkroom.codec.spi.RawImageReaderSpiSupport
rename it.tidalwave.imageio.raw.RAWImageReaderSupport 	org.rawdarkroom.codec.spi.RawImageReaderSupport
rename it.tidalwave.imageio.raw.RAWMetadataSupport 	org.rawdarkroom.metadata.RawMetadata
rename it.tidalwave.imageio.raw.RasterReader 	org.rawdarkroom.codec.spi.RasterReader
rename it.tidalwave.imageio.raw.Source 	org.rawdarkroom.Source
rename it.tidalwave.imageio.raw.TagRational 	org.rawdarkroom.metadata.TagRational
rename it.tidalwave.imageio.raw.TagRegistry 	org.rawdarkroom.metadata.tiff.TagRegistry
rename it.tidalwave.imageio.raw.Version 	org.rawdarkroom.impl.Version
rename it.tidalwave.imageio.rawprocessor.RAWProcessorInstallerSpi 	org.rawdarkroom.processor.RawProcessorInstallerSpi
rename it.tidalwave.imageio.srf.SRFImageInputStream 	org.rawdarkroom.codec.impl.sony.SrfImageInputStream
rename it.tidalwave.imageio.srf.SRFImageReader 	org.rawdarkroom.codec.impl.sony.SrfImageReader
rename it.tidalwave.imageio.srf.SRFImageReaderSpi 	org.rawdarkroom.codec.impl.sony.SrfImageReaderSpi
rename it.tidalwave.imageio.srf.SRFMetadata 	org.rawdarkroom.metadata.sony.SrfMetadata
rename it.tidalwave.imageio.srf.SRFRasterReader 	org.rawdarkroom.codec.impl.sony.SrfRasterReader
rename it.tidalwave.imageio.srf.SonyDecipher 	org.rawdarkroom.codec.impl.sony.SonyDecipher
rename it.tidalwave.imageio.srf.SonyMakerNote 	org.rawdarkroom.metadata.sony.SonyMakerNote
rename it.tidalwave.imageio.srf.SonySRF0 	org.rawdarkroom.metadata.sony.SonySrf0
rename it.tidalwave.imageio.srf.SonySRF1 	org.rawdarkroom.metadata.sony.SonySrf1
rename it.tidalwave.imageio.srf.SonySRF2 	org.rawdarkroom.metadata.sony.SonySrf2
rename it.tidalwave.imageio.srf.SonySRF3 	org.rawdarkroom.metadata.sony.SonySrf3
rename it.tidalwave.imageio.srf.SonySRF4 	org.rawdarkroom.metadata.sony.SonySrf4
rename it.tidalwave.imageio.srf.SonySRF5 	org.rawdarkroom.metadata.sony.SonySrf5
rename it.tidalwave.imageio.srf.SonySRF6 	org.rawdarkroom.metadata.sony.SonySrf6
rename it.tidalwave.imageio.tiff.IFD 	org.rawdarkroom.metadata.tiff.Ifd
rename it.tidalwave.imageio.tiff.IFDSupport 	org.rawdarkroom.metadata.tiff.impl.IfdSupport
rename it.tidalwave.imageio.tiff.TIFFImageReaderSupport 	org.rawdarkroom.metadata.tiff.TiffImageReaderSupport
rename it.tidalwave.imageio.tiff.TIFFMetadataSupport 	org.rawdarkroom.metadata.tiff.TiffMetadataSupport
rename it.tidalwave.imageio.tiff.TIFFTag 	org.rawdarkroom.metadata.tiff.TiffTag
rename it.tidalwave.imageio.tiff.ThumbnailLoader 	org.rawdarkroom.spi.ThumbnailLoader
rename it.tidalwave.imageio.util.DefaultLookup 	org.rawdarkroom.spi.DefaultLookup
rename it.tidalwave.imageio.util.DefaultingLookup 	org.rawdarkroom.spi.DefaultingLookup
rename it.tidalwave.imageio.util.Logger 	org.rawdarkroom.impl.Logger
rename it.tidalwave.imageio.util.Lookup 	org.rawdarkroom.spi.Lookup
rename it.tidalwave.imageio.util.VersionLoader 	org.rawdarkroom.impl.VersionLoader

cd $PWD/modules/processor

rename it.tidalwave.imageio.nef.NikonCaptureEditorMetadata 	org.rawdarkroom.metadata.nikon.NikonSoftwareMetadata
rename it.tidalwave.imageio.rawprocessor.ColorMatrix 	org.rawdarkroom.processor.ColorMatrix
rename it.tidalwave.imageio.rawprocessor.Curve 	org.rawdarkroom.processor.impl.Curve
rename it.tidalwave.imageio.rawprocessor.Operation 	org.rawdarkroom.processor.impl.Operation
rename it.tidalwave.imageio.rawprocessor.OperationSupport 	org.rawdarkroom.processor.impl.OperationSupport
rename it.tidalwave.imageio.rawprocessor.PipelineArtifact 	org.rawdarkroom.processor.impl.PipelineArtifact
rename it.tidalwave.imageio.rawprocessor.RAWProcessor 	org.rawdarkroom.processor.impl.RawProcessor
rename it.tidalwave.imageio.rawprocessor.RAWProcessorInstaller 	org.rawdarkroom.processor.impl.RawProcessorInstaller
rename it.tidalwave.imageio.rawprocessor.Version 	org.rawdarkroom.processor.impl.Version
rename it.tidalwave.imageio.rawprocessor.arw.ARWCurveOperation 	org.rawdarkroom.processor.impl.minolta.ArwCurveOperation
rename it.tidalwave.imageio.rawprocessor.arw.ARWProcessor 	org.rawdarkroom.processor.impl.minolta.ArwProcessor
rename it.tidalwave.imageio.rawprocessor.arw.ARWSizeOperation 	org.rawdarkroom.processor.impl.minolta.ArwSizeOperation
rename it.tidalwave.imageio.rawprocessor.arw.ARWWhiteBalanceOperation 	org.rawdarkroom.processor.impl.minolta.ArwWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2ColorConversionOperation 	org.rawdarkroom.processor.impl.canon.Cr2ColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2CurveOperation 	org.rawdarkroom.processor.impl.canon.Cr2CurveOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2Processor 	org.rawdarkroom.processor.impl.canon.Cr2Processor
rename it.tidalwave.imageio.rawprocessor.cr2.CR2SizeOperation 	org.rawdarkroom.processor.impl.canon.Cr2SizeOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2WhiteBalanceOperation 	org.rawdarkroom.processor.impl.canon.Cr2WhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWColorConversionOperation 	org.rawdarkroom.processor.impl.canon.CrwColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWCurveOperation 	org.rawdarkroom.processor.impl.canon.CrwCurveOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWProcessor 	org.rawdarkroom.processor.impl.canon.CrwProcessor
rename it.tidalwave.imageio.rawprocessor.crw.CRWSizeOperation 	org.rawdarkroom.processor.impl.canon.CrwSizeOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWWhiteBalanceOperation 	org.rawdarkroom.processor.impl.canon.CrwWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo 	org.rawdarkroom.processor.impl.demosaic.BayerInfo
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_BGGR 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_BGGR
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_GBRG 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_GBRG
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_GRBG 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_GRBG
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_RGGB 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_RGGB
rename it.tidalwave.imageio.rawprocessor.demosaic.BilinearDemosaicingFilter 	org.rawdarkroom.processor.impl.demosaic.BilinearDemosaicingFilter
rename it.tidalwave.imageio.rawprocessor.demosaic.DemosaicFilterProcessor 	org.rawdarkroom.processor.impl.demosaic.DemosaicFilterProcessor
rename it.tidalwave.imageio.rawprocessor.demosaic.DemosaicingFilter 	org.rawdarkroom.processor.impl.demosaic.DemosaicingFilter
rename it.tidalwave.imageio.rawprocessor.demosaic.PixelGroupingDemosaicingFilter 	org.rawdarkroom.processor.impl.demosaic.PixelGroupingDemosaicingFilter
rename it.tidalwave.imageio.rawprocessor.dng.DNGColorConversionOperation 	org.rawdarkroom.processor.impl.adobe.DngColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.dng.DNGCurveOperation 	org.rawdarkroom.processor.impl.adobe.DngCurveOperation
rename it.tidalwave.imageio.rawprocessor.dng.DNGProcessor 	org.rawdarkroom.processor.impl.adobe.DngProcessor
rename it.tidalwave.imageio.rawprocessor.dng.DNGSizeOperation 	org.rawdarkroom.processor.impl.adobe.DngSizeOperation
rename it.tidalwave.imageio.rawprocessor.dng.DNGWhiteBalanceOperation 	org.rawdarkroom.processor.impl.adobe.DngWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.mrw.MRWCurveOperation 	org.rawdarkroom.processor.impl.minolta.MrwCurveOperation
rename it.tidalwave.imageio.rawprocessor.mrw.MRWProcessor 	org.rawdarkroom.processor.impl.minolta.MrwProcessor
rename it.tidalwave.imageio.rawprocessor.mrw.MRWSizeOperation 	org.rawdarkroom.processor.impl.minolta.MrwSizeOperation
rename it.tidalwave.imageio.rawprocessor.mrw.MRWWhiteBalanceOperation 	org.rawdarkroom.processor.impl.minolta.MrwWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFColorConversionOperation 	org.rawdarkroom.processor.impl.nikon.NefColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFCurveOperation 	org.rawdarkroom.processor.impl.nikon.NefCurveOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFExposureOperation 	org.rawdarkroom.processor.impl.nikon.NefExposureOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFProcessor 	org.rawdarkroom.processor.impl.nikon.NefProcessor
rename it.tidalwave.imageio.rawprocessor.nef.NEFRotateOperation 	org.rawdarkroom.processor.impl.nikon.NefRotateOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFSizeOperation 	org.rawdarkroom.processor.impl.nikon.NefSizeOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.nikon.NefWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFColorConversionOperation 	org.rawdarkroom.processor.impl.olympus.OrfColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFCurveOperation 	org.rawdarkroom.processor.impl.olympus.OrfCurveOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFProcessor 	org.rawdarkroom.processor.impl.olympus.OrfProcessor
rename it.tidalwave.imageio.rawprocessor.orf.ORFSizeOperation 	org.rawdarkroom.processor.impl.olympus.OrfSizeOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.olympus.OrfWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.pef.PEFCurveOperation 	org.rawdarkroom.processor.impl.pentax.PefCurveOperation
rename it.tidalwave.imageio.rawprocessor.pef.PEFProcessor 	org.rawdarkroom.processor.impl.pentax.PefProcessor
rename it.tidalwave.imageio.rawprocessor.pef.PEFSizeOperation 	org.rawdarkroom.processor.impl.pentax.PefSizeOperation
rename it.tidalwave.imageio.rawprocessor.pef.PEFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.pentax.PefWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFCurveOperation 	org.rawdarkroom.processor.impl.fuji.RafCurveOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFDemosaicOperation 	org.rawdarkroom.processor.impl.fuji.RafDemosaicOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFProcessor 	org.rawdarkroom.processor.impl.fuji.RafProcessor
rename it.tidalwave.imageio.rawprocessor.raf.RAFRotateOperation 	org.rawdarkroom.processor.impl.fuji.RafRotateOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFSizeOperation 	org.rawdarkroom.processor.impl.fuji.RafSizeOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.fuji.RafWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.raw.ColorConversionOperation 	org.rawdarkroom.processor.impl.ColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.raw.ColorProfileOperation 	org.rawdarkroom.processor.impl.ColorProfileOperation
rename it.tidalwave.imageio.rawprocessor.raw.CurveOperation 	org.rawdarkroom.processor.impl.CurveOperation
rename it.tidalwave.imageio.rawprocessor.raw.DemosaicOperation 	org.rawdarkroom.processor.impl.DemosaicOperation
rename it.tidalwave.imageio.rawprocessor.raw.ExposureOperation 	org.rawdarkroom.processor.impl.ExposureOperation
rename it.tidalwave.imageio.rawprocessor.raw.RotateOperation 	org.rawdarkroom.processor.impl.RotateOperation
rename it.tidalwave.imageio.rawprocessor.raw.SharpenOperation 	org.rawdarkroom.processor.impl.SharpenOperation
rename it.tidalwave.imageio.rawprocessor.raw.SizeOperation 	org.rawdarkroom.processor.impl.SizeOperation
rename it.tidalwave.imageio.rawprocessor.raw.WhiteBalanceOperation 	org.rawdarkroom.processor.impl.WhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.srf.SRFProcessor 	org.rawdarkroom.processor.impl.sony.SrfProcessor 	org.rawdarkroom.codec.impl.minolta.ArwImageReader
rename it.tidalwave.imageio.arw.ARWImageReaderSpi 	org.rawdarkroom.codec.impl.minolta.ArwImageReaderSpi
rename it.tidalwave.imageio.arw.ARWMakerNote 	org.rawdarkroom.metadata.minolta.ArwMakerNote
rename it.tidalwave.imageio.arw.ARWMetadata 	org.rawdarkroom.metadata.minolta.ArwMetadata
rename it.tidalwave.imageio.arw.ARWRasterReader 	org.rawdarkroom.codec.impl.minolta.ArwRasterReader
rename it.tidalwave.imageio.cr2.CR2ImageReader 	org.rawdarkroom.codec.impl.canon.Cr2ImageReader
rename it.tidalwave.imageio.cr2.CR2ImageReaderSpi 	org.rawdarkroom.codec.impl.canon.Cr2ImageReaderSpi
rename it.tidalwave.imageio.cr2.CR2Metadata 	org.rawdarkroom.metadata.canon.Cr2Metadata
rename it.tidalwave.imageio.cr2.CR2RasterReader 	org.rawdarkroom.codec.impl.canon.Cr2RasterReader
rename it.tidalwave.imageio.cr2.CR2SensorInfo 	org.rawdarkroom.metadata.canon.Cr2SensorInfo
rename it.tidalwave.imageio.cr2.CanonCR2MakerNote 	org.rawdarkroom.metadata.canon.CanonCr2MakerNote
rename it.tidalwave.imageio.crw.CIFFTag 	org.rawdarkroom.metadata.canon.CiffTag
rename it.tidalwave.imageio.crw.CRWImageInputStream 	org.rawdarkroom.codec.impl.canon.CrwImageInputStream
rename it.tidalwave.imageio.crw.CRWImageReader 	org.rawdarkroom.codec.impl.canon.CrwImageReader
rename it.tidalwave.imageio.crw.CRWImageReaderSpi 	org.rawdarkroom.codec.impl.canon.CrwImageReaderSpi
rename it.tidalwave.imageio.crw.CRWRasterReader 	org.rawdarkroom.codec.impl.canon.CrwRasterReader
rename it.tidalwave.imageio.crw.CanonCRWMakerNote 	org.rawdarkroom.metadata.canon.CanonCrwMakerNote
rename it.tidalwave.imageio.dcr.DCRImageReader 	org.rawdarkroom.codec.impl.kodak.DcrImageReader
rename it.tidalwave.imageio.dcr.DCRImageReaderSpi 	org.rawdarkroom.codec.impl.kodak.DcrImageReaderSpi
rename it.tidalwave.imageio.dcr.DCRMetadata 	org.rawdarkroom.metadata.kodak.DcrMetadata
rename it.tidalwave.imageio.dcr.DCRRasterReader 	org.rawdarkroom.codec.impl.kodak.DcrRasterReader
rename it.tidalwave.imageio.dcr.KodakMakerNote 	org.rawdarkroom.metadata.kodak.KodakDcrMakerNote
rename it.tidalwave.imageio.decoder.HuffmannDecoder 	org.rawdarkroom.spi.decoder.HuffmannDecoder
rename it.tidalwave.imageio.decoder.LosslessJPEGDecoder 	org.rawdarkroom.spi.decoder.LosslessJpegDecoder
rename it.tidalwave.imageio.dng.DNGImageReader 	org.rawdarkroom.codec.impl.adobe.DngImageReader
rename it.tidalwave.imageio.dng.DNGImageReaderSpi 	org.rawdarkroom.codec.impl.adobe.DngImageReaderSpi
rename it.tidalwave.imageio.dng.DNGMetadata 	org.rawdarkroom.metadata.adobe.DngMetadata
rename it.tidalwave.imageio.dng.DNGRasterReader 	org.rawdarkroom.codec.impl.adobe.DngRasterReader
rename it.tidalwave.imageio.io.BitReader 	org.rawdarkroom.spi.codec.BitReader
rename it.tidalwave.imageio.io.FastBitReader 	org.rawdarkroom.spi.codec.FastBitReader
rename it.tidalwave.imageio.io.FileImageInputStream2 	org.rawdarkroom.spi.codec.FileImageInputStream2
rename it.tidalwave.imageio.io.FileImageInputStream2Spi 	org.rawdarkroom.spi.codec.FileImageInputStream2Spi
rename it.tidalwave.imageio.io.RAWImageInputStream 	org.rawdarkroom.spi.codec.RawImageInputStream
rename it.tidalwave.imageio.io.RAWImageInputStreamImpl 	org.rawdarkroom.spi.codec.RawImageInputStreamImpl
rename it.tidalwave.imageio.io.SixteenBitsReader 	org.rawdarkroom.spi.codec.SixteenBitsReader
rename it.tidalwave.imageio.io.TwelveBitsReader 	org.rawdarkroom.spi.codec.TwelveBitsReader
rename it.tidalwave.imageio.makernote.LeicaMakerNote 	org.rawdarkroom.metadata.leica.LeicaMakerNote
rename it.tidalwave.imageio.minolta.MinoltaRawData 	org.rawdarkroom.metadata.minolta.MinoltaRawData
rename it.tidalwave.imageio.mrw.MRWHeaderProcessor 	org.rawdarkroom.codec.impl.MrwHeaderProcessor
rename it.tidalwave.imageio.mrw.MRWImageReader 	org.rawdarkroom.codec.impl.MrwImageReader
rename it.tidalwave.imageio.mrw.MRWImageReaderSpi 	org.rawdarkroom.codec.impl.MrwImageReaderSpi
rename it.tidalwave.imageio.mrw.MRWMetadata 	org.rawdarkroom.metadata.minolta.MrwMetadata
rename it.tidalwave.imageio.mrw.MRWRasterReader 	org.rawdarkroom.codec.impl.minolta.MrwRasterReader
rename it.tidalwave.imageio.mrw.MinoltaMakerNote 	org.rawdarkroom.metadata.minolta.MinoltaMakerNote
rename it.tidalwave.imageio.nef.NDFRasterReader 	org.rawdarkroom.codec.impl.nikon.NdfRasterReader
rename it.tidalwave.imageio.nef.NEFHeaderProcessor 	org.rawdarkroom.codec.impl.nikon.NefHeaderProcessor
rename it.tidalwave.imageio.nef.NEFImageReader 	org.rawdarkroom.codec.impl.nikon.NefImageReader
rename it.tidalwave.imageio.nef.NEFImageReaderSpi 	org.rawdarkroom.codec.impl.nikon.NefImageReaderSpi
rename it.tidalwave.imageio.nef.NEFLinearizationTable 	org.rawdarkroom.metadata.nikon.NefLinearizationTable
rename it.tidalwave.imageio.nef.NEFMetadata 	org.rawdarkroom.metadata.nikon.NefMetadata
rename it.tidalwave.imageio.nef.NEFRasterReader 	org.rawdarkroom.codec.impl.nikon.NefRasterReader
rename it.tidalwave.imageio.nef.NEFWhiteBalanceInfo 	org.rawdarkroom.metadata.nikon.NefWhiteBalanceInfo
rename it.tidalwave.imageio.nef.NikonLensInfo 	org.rawdarkroom.metadata.nikon.NikonLensInfo
rename it.tidalwave.imageio.nef.NikonMakerNote3 	org.rawdarkroom.metadata.nikon.NikonMakerNote3
rename it.tidalwave.imageio.nef.RasterReaderCoolpix 	org.rawdarkroom.codec.impl.nikon.RasterReaderCoolpix
rename it.tidalwave.imageio.nef.RasterReader_NIKON_D100 	org.rawdarkroom.codec.impl.nikon.RasterReader_NIKON_D100
rename it.tidalwave.imageio.nef.RasterReader_NIKON_D3 	org.rawdarkroom.codec.impl.nikon.RasterReader_NIKON_D3
rename it.tidalwave.imageio.orf.CSeriesRasterReader 	org.rawdarkroom.codec.impl.olympus.CSeriesRasterReader
rename it.tidalwave.imageio.orf.CameraSettings 	org.rawdarkroom.metadata.olympus.CameraSettings
rename it.tidalwave.imageio.orf.E300RasterReader 	org.rawdarkroom.codec.impl.olympus.E300RasterReader
rename it.tidalwave.imageio.orf.E410RasterReader 	org.rawdarkroom.codec.impl.olympus.E410RasterReader
rename it.tidalwave.imageio.orf.Equipment 	org.rawdarkroom.metadata.olympus.Equipment
rename it.tidalwave.imageio.orf.FocusInfo 	org.rawdarkroom.metadata.olympus.FocusInfo
rename it.tidalwave.imageio.orf.ImageProcessing 	org.rawdarkroom.metadata.olympus.ImageProcessing
rename it.tidalwave.imageio.orf.ORFImageReader 	org.rawdarkroom.codec.impl.olympus.OrfImageReader
rename it.tidalwave.imageio.orf.ORFImageReaderSpi 	org.rawdarkroom.codec.impl.olympus.OrfImageReaderSpi
rename it.tidalwave.imageio.orf.ORFMetadata 	org.rawdarkroom.metadata.olympus.OrfMetadata
rename it.tidalwave.imageio.orf.ORFRasterReader 	org.rawdarkroom.codec.impl.olympus.OrfRasterReader
rename it.tidalwave.imageio.orf.OlympusMakerNote 	org.rawdarkroom.metadata.olympus.OlympusMakerNote
rename it.tidalwave.imageio.orf.RawDevelopment 	org.rawdarkroom.metadata.olympus.RawDevelopment
rename it.tidalwave.imageio.orf.SPRasterReader 	org.rawdarkroom.codec.impl.olympus.SPRasterReader
rename it.tidalwave.imageio.pef.PEFDecoder 	org.rawdarkroom.codec.impl.pentax.PefDecoder
rename it.tidalwave.imageio.pef.PEFImageReader 	org.rawdarkroom.codec.impl.pentax.PefImageReader
rename it.tidalwave.imageio.pef.PEFImageReaderSpi 	org.rawdarkroom.codec.impl.pentax.PefImageReaderSpi
rename it.tidalwave.imageio.pef.PEFMetadata 	org.rawdarkroom.metadata.pentax.PefMetadata
rename it.tidalwave.imageio.pef.PEFRasterReader 	org.rawdarkroom.codec.impl.pentax.PefRasterReader
rename it.tidalwave.imageio.pef.PentaxMakerNote 	org.rawdarkroom.metadata.pentax.PentaxMakerNote
rename it.tidalwave.imageio.raf.FujiMakerNote 	org.rawdarkroom.metadata.fuji.FujiMakerNote
rename it.tidalwave.imageio.raf.FujiRawData 	org.rawdarkroom.metadata.fuji.FujiRawData
rename it.tidalwave.imageio.raf.FujiTable1 	org.rawdarkroom.metadata.fuji.FujiTable1
rename it.tidalwave.imageio.raf.RAFHeaderProcessor 	org.rawdarkroom.codec.impl.fuji.RafHeaderProcessor
rename it.tidalwave.imageio.raf.RAFImageReader 	org.rawdarkroom.codec.impl.fuji.RafImageReader
rename it.tidalwave.imageio.raf.RAFImageReaderSpi 	org.rawdarkroom.codec.impl.fuji.RafImageReaderSpi
rename it.tidalwave.imageio.raf.RAFMetadata 	org.rawdarkroom.metadata.fuji.RafMetadata
rename it.tidalwave.imageio.raf.RAFRasterReader 	org.rawdarkroom.codec.impl.fuji.RafRasterReader
rename it.tidalwave.imageio.raw.AbstractTag 	org.rawdarkroom.metadata.AbstractTag
rename it.tidalwave.imageio.raw.Directory 	org.rawdarkroom.metadata.Directory
rename it.tidalwave.imageio.raw.HeaderProcessor 	org.rawdarkroom.codec.spi.HeaderProcessor
rename it.tidalwave.imageio.raw.Packed12RasterReader 	org.rawdarkroom.codec.spi.Packed12RasterReader
rename it.tidalwave.imageio.raw.PostProcessor 	org.rawdarkroom.processor.Processor
rename it.tidalwave.imageio.raw.RAWImageReadParam 	org.rawdarkroom.RawImageReadParam
rename it.tidalwave.imageio.raw.RAWImageReaderSpiSupport 	org.rawdarkroom.codec.spi.RawImageReaderSpiSupport
rename it.tidalwave.imageio.raw.RAWImageReaderSupport 	org.rawdarkroom.codec.spi.RawImageReaderSupport
rename it.tidalwave.imageio.raw.RAWMetadataSupport 	org.rawdarkroom.metadata.RawMetadata
rename it.tidalwave.imageio.raw.RasterReader 	org.rawdarkroom.codec.spi.RasterReader
rename it.tidalwave.imageio.raw.Source 	org.rawdarkroom.Source
rename it.tidalwave.imageio.raw.TagRational 	org.rawdarkroom.metadata.TagRational
rename it.tidalwave.imageio.raw.TagRegistry 	org.rawdarkroom.metadata.tiff.TagRegistry
rename it.tidalwave.imageio.raw.Version 	org.rawdarkroom.impl.Version
rename it.tidalwave.imageio.rawprocessor.RAWProcessorInstallerSpi 	org.rawdarkroom.processor.RawProcessorInstallerSpi
rename it.tidalwave.imageio.srf.SRFImageInputStream 	org.rawdarkroom.codec.impl.sony.SrfImageInputStream
rename it.tidalwave.imageio.srf.SRFImageReader 	org.rawdarkroom.codec.impl.sony.SrfImageReader
rename it.tidalwave.imageio.srf.SRFImageReaderSpi 	org.rawdarkroom.codec.impl.sony.SrfImageReaderSpi
rename it.tidalwave.imageio.srf.SRFMetadata 	org.rawdarkroom.metadata.sony.SrfMetadata
rename it.tidalwave.imageio.srf.SRFRasterReader 	org.rawdarkroom.codec.impl.sony.SrfRasterReader
rename it.tidalwave.imageio.srf.SonyDecipher 	org.rawdarkroom.codec.impl.sony.SonyDecipher
rename it.tidalwave.imageio.srf.SonyMakerNote 	org.rawdarkroom.metadata.sony.SonyMakerNote
rename it.tidalwave.imageio.srf.SonySRF0 	org.rawdarkroom.metadata.sony.SonySrf0
rename it.tidalwave.imageio.srf.SonySRF1 	org.rawdarkroom.metadata.sony.SonySrf1
rename it.tidalwave.imageio.srf.SonySRF2 	org.rawdarkroom.metadata.sony.SonySrf2
rename it.tidalwave.imageio.srf.SonySRF3 	org.rawdarkroom.metadata.sony.SonySrf3
rename it.tidalwave.imageio.srf.SonySRF4 	org.rawdarkroom.metadata.sony.SonySrf4
rename it.tidalwave.imageio.srf.SonySRF5 	org.rawdarkroom.metadata.sony.SonySrf5
rename it.tidalwave.imageio.srf.SonySRF6 	org.rawdarkroom.metadata.sony.SonySrf6
rename it.tidalwave.imageio.tiff.IFD 	org.rawdarkroom.metadata.tiff.Ifd
rename it.tidalwave.imageio.tiff.IFDSupport 	org.rawdarkroom.metadata.tiff.impl.IfdSupport
rename it.tidalwave.imageio.tiff.TIFFImageReaderSupport 	org.rawdarkroom.metadata.tiff.TiffImageReaderSupport
rename it.tidalwave.imageio.tiff.TIFFMetadataSupport 	org.rawdarkroom.metadata.tiff.TiffMetadataSupport
rename it.tidalwave.imageio.tiff.TIFFTag 	org.rawdarkroom.metadata.tiff.TiffTag
rename it.tidalwave.imageio.tiff.ThumbnailLoader 	org.rawdarkroom.spi.ThumbnailLoader
rename it.tidalwave.imageio.util.DefaultLookup 	org.rawdarkroom.spi.DefaultLookup
rename it.tidalwave.imageio.util.DefaultingLookup 	org.rawdarkroom.spi.DefaultingLookup
rename it.tidalwave.imageio.util.Logger 	org.rawdarkroom.impl.Logger
rename it.tidalwave.imageio.util.Lookup 	org.rawdarkroom.spi.Lookup
rename it.tidalwave.imageio.util.VersionLoader 	org.rawdarkroom.impl.VersionLoader

rename it.tidalwave.imageio.nef.NikonCaptureEditorMetadata 	org.rawdarkroom.metadata.nikon.NikonSoftwareMetadata
rename it.tidalwave.imageio.rawprocessor.ColorMatrix 	org.rawdarkroom.processor.ColorMatrix
rename it.tidalwave.imageio.rawprocessor.Curve 	org.rawdarkroom.processor.impl.Curve
rename it.tidalwave.imageio.rawprocessor.Operation 	org.rawdarkroom.processor.impl.Operation
rename it.tidalwave.imageio.rawprocessor.OperationSupport 	org.rawdarkroom.processor.impl.OperationSupport
rename it.tidalwave.imageio.rawprocessor.PipelineArtifact 	org.rawdarkroom.processor.impl.PipelineArtifact
rename it.tidalwave.imageio.rawprocessor.RAWProcessor 	org.rawdarkroom.processor.impl.RawProcessor
rename it.tidalwave.imageio.rawprocessor.RAWProcessorInstaller 	org.rawdarkroom.processor.impl.RawProcessorInstaller
rename it.tidalwave.imageio.rawprocessor.Version 	org.rawdarkroom.processor.impl.Version
rename it.tidalwave.imageio.rawprocessor.arw.ARWCurveOperation 	org.rawdarkroom.processor.impl.minolta.ArwCurveOperation
rename it.tidalwave.imageio.rawprocessor.arw.ARWProcessor 	org.rawdarkroom.processor.impl.minolta.ArwProcessor
rename it.tidalwave.imageio.rawprocessor.arw.ARWSizeOperation 	org.rawdarkroom.processor.impl.minolta.ArwSizeOperation
rename it.tidalwave.imageio.rawprocessor.arw.ARWWhiteBalanceOperation 	org.rawdarkroom.processor.impl.minolta.ArwWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2ColorConversionOperation 	org.rawdarkroom.processor.impl.canon.Cr2ColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2CurveOperation 	org.rawdarkroom.processor.impl.canon.Cr2CurveOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2Processor 	org.rawdarkroom.processor.impl.canon.Cr2Processor
rename it.tidalwave.imageio.rawprocessor.cr2.CR2SizeOperation 	org.rawdarkroom.processor.impl.canon.Cr2SizeOperation
rename it.tidalwave.imageio.rawprocessor.cr2.CR2WhiteBalanceOperation 	org.rawdarkroom.processor.impl.canon.Cr2WhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWColorConversionOperation 	org.rawdarkroom.processor.impl.canon.CrwColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWCurveOperation 	org.rawdarkroom.processor.impl.canon.CrwCurveOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWProcessor 	org.rawdarkroom.processor.impl.canon.CrwProcessor
rename it.tidalwave.imageio.rawprocessor.crw.CRWSizeOperation 	org.rawdarkroom.processor.impl.canon.CrwSizeOperation
rename it.tidalwave.imageio.rawprocessor.crw.CRWWhiteBalanceOperation 	org.rawdarkroom.processor.impl.canon.CrwWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo 	org.rawdarkroom.processor.impl.demosaic.BayerInfo
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_BGGR 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_BGGR
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_GBRG 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_GBRG
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_GRBG 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_GRBG
rename it.tidalwave.imageio.rawprocessor.demosaic.BayerInfo_RGGB 	org.rawdarkroom.processor.impl.demosaic.BayerInfo_RGGB
rename it.tidalwave.imageio.rawprocessor.demosaic.BilinearDemosaicingFilter 	org.rawdarkroom.processor.impl.demosaic.BilinearDemosaicingFilter
rename it.tidalwave.imageio.rawprocessor.demosaic.DemosaicFilterProcessor 	org.rawdarkroom.processor.impl.demosaic.DemosaicFilterProcessor
rename it.tidalwave.imageio.rawprocessor.demosaic.DemosaicingFilter 	org.rawdarkroom.processor.impl.demosaic.DemosaicingFilter
rename it.tidalwave.imageio.rawprocessor.demosaic.PixelGroupingDemosaicingFilter 	org.rawdarkroom.processor.impl.demosaic.PixelGroupingDemosaicingFilter
rename it.tidalwave.imageio.rawprocessor.dng.DNGColorConversionOperation 	org.rawdarkroom.processor.impl.adobe.DngColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.dng.DNGCurveOperation 	org.rawdarkroom.processor.impl.adobe.DngCurveOperation
rename it.tidalwave.imageio.rawprocessor.dng.DNGProcessor 	org.rawdarkroom.processor.impl.adobe.DngProcessor
rename it.tidalwave.imageio.rawprocessor.dng.DNGSizeOperation 	org.rawdarkroom.processor.impl.adobe.DngSizeOperation
rename it.tidalwave.imageio.rawprocessor.dng.DNGWhiteBalanceOperation 	org.rawdarkroom.processor.impl.adobe.DngWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.mrw.MRWCurveOperation 	org.rawdarkroom.processor.impl.minolta.MrwCurveOperation
rename it.tidalwave.imageio.rawprocessor.mrw.MRWProcessor 	org.rawdarkroom.processor.impl.minolta.MrwProcessor
rename it.tidalwave.imageio.rawprocessor.mrw.MRWSizeOperation 	org.rawdarkroom.processor.impl.minolta.MrwSizeOperation
rename it.tidalwave.imageio.rawprocessor.mrw.MRWWhiteBalanceOperation 	org.rawdarkroom.processor.impl.minolta.MrwWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFColorConversionOperation 	org.rawdarkroom.processor.impl.nikon.NefColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFCurveOperation 	org.rawdarkroom.processor.impl.nikon.NefCurveOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFExposureOperation 	org.rawdarkroom.processor.impl.nikon.NefExposureOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFProcessor 	org.rawdarkroom.processor.impl.nikon.NefProcessor
rename it.tidalwave.imageio.rawprocessor.nef.NEFRotateOperation 	org.rawdarkroom.processor.impl.nikon.NefRotateOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFSizeOperation 	org.rawdarkroom.processor.impl.nikon.NefSizeOperation
rename it.tidalwave.imageio.rawprocessor.nef.NEFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.nikon.NefWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFColorConversionOperation 	org.rawdarkroom.processor.impl.olympus.OrfColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFCurveOperation 	org.rawdarkroom.processor.impl.olympus.OrfCurveOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFProcessor 	org.rawdarkroom.processor.impl.olympus.OrfProcessor
rename it.tidalwave.imageio.rawprocessor.orf.ORFSizeOperation 	org.rawdarkroom.processor.impl.olympus.OrfSizeOperation
rename it.tidalwave.imageio.rawprocessor.orf.ORFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.olympus.OrfWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.pef.PEFCurveOperation 	org.rawdarkroom.processor.impl.pentax.PefCurveOperation
rename it.tidalwave.imageio.rawprocessor.pef.PEFProcessor 	org.rawdarkroom.processor.impl.pentax.PefProcessor
rename it.tidalwave.imageio.rawprocessor.pef.PEFSizeOperation 	org.rawdarkroom.processor.impl.pentax.PefSizeOperation
rename it.tidalwave.imageio.rawprocessor.pef.PEFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.pentax.PefWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFCurveOperation 	org.rawdarkroom.processor.impl.fuji.RafCurveOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFDemosaicOperation 	org.rawdarkroom.processor.impl.fuji.RafDemosaicOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFProcessor 	org.rawdarkroom.processor.impl.fuji.RafProcessor
rename it.tidalwave.imageio.rawprocessor.raf.RAFRotateOperation 	org.rawdarkroom.processor.impl.fuji.RafRotateOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFSizeOperation 	org.rawdarkroom.processor.impl.fuji.RafSizeOperation
rename it.tidalwave.imageio.rawprocessor.raf.RAFWhiteBalanceOperation 	org.rawdarkroom.processor.impl.fuji.RafWhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.raw.ColorConversionOperation 	org.rawdarkroom.processor.impl.ColorConversionOperation
rename it.tidalwave.imageio.rawprocessor.raw.ColorProfileOperation 	org.rawdarkroom.processor.impl.ColorProfileOperation
rename it.tidalwave.imageio.rawprocessor.raw.CurveOperation 	org.rawdarkroom.processor.impl.CurveOperation
rename it.tidalwave.imageio.rawprocessor.raw.DemosaicOperation 	org.rawdarkroom.processor.impl.DemosaicOperation
rename it.tidalwave.imageio.rawprocessor.raw.ExposureOperation 	org.rawdarkroom.processor.impl.ExposureOperation
rename it.tidalwave.imageio.rawprocessor.raw.RotateOperation 	org.rawdarkroom.processor.impl.RotateOperation
rename it.tidalwave.imageio.rawprocessor.raw.SharpenOperation 	org.rawdarkroom.processor.impl.SharpenOperation
rename it.tidalwave.imageio.rawprocessor.raw.SizeOperation 	org.rawdarkroom.processor.impl.SizeOperation
rename it.tidalwave.imageio.rawprocessor.raw.WhiteBalanceOperation 	org.rawdarkroom.processor.impl.WhiteBalanceOperation
rename it.tidalwave.imageio.rawprocessor.srf.SRFProcessor 	org.rawdarkroom.processor.impl.sony.SrfProcessor
